package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a default config file",
	Long:  `Generate a default cc-relay configuration file at ~/.config/cc-relay/config.yaml`,
	RunE:  runConfigInit,
}

func init() {
	configCmd.AddCommand(configInitCmd)
	configInitCmd.Flags().StringP("output", "o", "", "output path (default: ~/.config/cc-relay/config.yaml)")
	configInitCmd.Flags().Bool("force", false, "overwrite existing config file")
}

func runConfigInit(cmd *cobra.Command, _ []string) error {
	output, _ := cmd.Flags().GetString("output")
	force, _ := cmd.Flags().GetBool("force")

	if output == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("failed to get home directory: %w", err)
		}
		output = filepath.Join(home, ".config", "cc-relay", "config.yaml")
	}

	// Check if file exists
	if _, err := os.Stat(output); err == nil && !force {
		return fmt.Errorf("config file already exists at %s (use --force to overwrite)", output)
	}

	// Create directory if needed
	dir := filepath.Dir(output)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write default config
	defaultConfig := `# cc-relay configuration
# Generated by 'cc-relay config init'
# For full configuration options, see: https://github.com/omarluq/cc-relay/blob/main/example.yaml

# ============================================================================
# Server Configuration
# ============================================================================
server:
  # Address to listen on (Claude Code connects here)
  listen: "127.0.0.1:8787"

  # Request timeout in milliseconds (10 minutes for long operations)
  timeout_ms: 600000

  # Enable HTTP/2 for better performance with concurrent requests
  enable_http2: true

  # --------------------------------------------------------------------------
  # Authentication
  # --------------------------------------------------------------------------
  auth:
    # Optional: Require specific API key for proxy access
    # api_key: "${PROXY_API_KEY}"

    # Allow Claude Code subscription tokens (passthrough mode)
    # Enable this if you use Claude Code with a subscription
    allow_subscription: true

# ============================================================================
# Routing Configuration
# ============================================================================
routing:
  # Available strategies: simple-shuffle, round-robin, least-busy, failover
  # simple-shuffle: Weighted random selection (recommended for most use cases)
  strategy: "simple-shuffle"

# ============================================================================
# Provider Configurations
# ============================================================================
providers:
  # --------------------------------------------------------------------------
  # Anthropic Direct API
  # --------------------------------------------------------------------------
  - name: "anthropic"
    type: "anthropic"
    enabled: true

    keys:
      - key: "${ANTHROPIC_API_KEY}"
        rpm_limit: 60          # Requests per minute
        tpm_limit: 100000      # Tokens per minute
      # Add more keys for rate limit pooling:
      # - key: "${ANTHROPIC_API_KEY_2}"
      #   rpm_limit: 60
      #   tpm_limit: 100000

  # --------------------------------------------------------------------------
  # Z.AI / Zhipu GLM (Optional - ~1/7 cost of Anthropic)
  # Uncomment to enable
  # --------------------------------------------------------------------------
  # - name: "zai"
  #   type: "zai"
  #   enabled: true
  #   base_url: "https://api.z.ai/api/anthropic"
  #
  #   keys:
  #     - key: "${ZAI_API_KEY}"
  #
  #   model_mapping:
  #     "claude-sonnet-4-5-20250929": "GLM-4.7"
  #     "claude-haiku-4-5-20251001": "GLM-4.5-Air"

  # --------------------------------------------------------------------------
  # Ollama (Optional - Local models)
  # Uncomment to enable
  # --------------------------------------------------------------------------
  # - name: "ollama"
  #   type: "ollama"
  #   enabled: true
  #   base_url: "http://localhost:11434"
  #
  #   model_mapping:
  #     "claude-sonnet-4-5-20250929": "qwen3:32b"
  #     "claude-haiku-4-5-20251001": "qwen3:8b"

# ============================================================================
# gRPC Management API (for TUI/CLI)
# ============================================================================
grpc:
  listen: "127.0.0.1:9090"

# ============================================================================
# Logging
# ============================================================================
logging:
  level: "info"          # Options: debug, info, warn, error
  format: "text"         # Options: json, text

# ============================================================================
# Metrics
# ============================================================================
metrics:
  enabled: true
  prometheus_endpoint: "/metrics"
  prometheus_listen: "127.0.0.1:9100"

# ============================================================================
# Health Checking
# ============================================================================
health:
  check_interval_seconds: 30

  circuit_breaker:
    failure_threshold: 5
    recovery_timeout_seconds: 60
    triggers:
      rate_limit_errors: 3
      timeout_errors: 2
      server_errors: 3
`

	if err := os.WriteFile(output, []byte(defaultConfig), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Printf("✓ Config file created at %s\n", output)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Set ANTHROPIC_API_KEY environment variable")
	fmt.Println("  2. Edit the config file to customize providers and routing")
	fmt.Println("  3. Validate with: cc-relay config validate")
	fmt.Println("  4. Start the proxy: cc-relay serve")
	fmt.Println("  5. Configure Claude Code: cc-relay config cc init")

	return nil
}
